//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.25 at 11:40:23 PM CEST 
//


package org.xmlreceipt.marshaller;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Xmlreceipt }
     * 
     */
    public Xmlreceipt createXmlreceipt() {
        return new Xmlreceipt();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Itemlist }
     * 
     */
    public Xmlreceipt.Itemlist createXmlreceiptItemlist() {
        return new Xmlreceipt.Itemlist();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Itemlist.Item }
     * 
     */
    public Xmlreceipt.Itemlist.Item createXmlreceiptItemlistItem() {
        return new Xmlreceipt.Itemlist.Item();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Itemlist.Item.Itemgroup }
     * 
     */
    public Xmlreceipt.Itemlist.Item.Itemgroup createXmlreceiptItemlistItemItemgroup() {
        return new Xmlreceipt.Itemlist.Item.Itemgroup();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Total }
     * 
     */
    public Xmlreceipt.Total createXmlreceiptTotal() {
        return new Xmlreceipt.Total();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Seller }
     * 
     */
    public Xmlreceipt.Seller createXmlreceiptSeller() {
        return new Xmlreceipt.Seller();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Itemlist.Item.Itemid }
     * 
     */
    public Xmlreceipt.Itemlist.Item.Itemid createXmlreceiptItemlistItemItemid() {
        return new Xmlreceipt.Itemlist.Item.Itemid();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Itemlist.Item.Dates }
     * 
     */
    public Xmlreceipt.Itemlist.Item.Dates createXmlreceiptItemlistItemDates() {
        return new Xmlreceipt.Itemlist.Item.Dates();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Itemlist.Item.Price }
     * 
     */
    public Xmlreceipt.Itemlist.Item.Price createXmlreceiptItemlistItemPrice() {
        return new Xmlreceipt.Itemlist.Item.Price();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Itemlist.Item.Quantity }
     * 
     */
    public Xmlreceipt.Itemlist.Item.Quantity createXmlreceiptItemlistItemQuantity() {
        return new Xmlreceipt.Itemlist.Item.Quantity();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Itemlist.Item.Infosheet }
     * 
     */
    public Xmlreceipt.Itemlist.Item.Infosheet createXmlreceiptItemlistItemInfosheet() {
        return new Xmlreceipt.Itemlist.Item.Infosheet();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Itemlist.Item.Aspect }
     * 
     */
    public Xmlreceipt.Itemlist.Item.Aspect createXmlreceiptItemlistItemAspect() {
        return new Xmlreceipt.Itemlist.Item.Aspect();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Itemlist.Item.Itemgroup.Eclass }
     * 
     */
    public Xmlreceipt.Itemlist.Item.Itemgroup.Eclass createXmlreceiptItemlistItemItemgroupEclass() {
        return new Xmlreceipt.Itemlist.Item.Itemgroup.Eclass();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Itemlist.Item.Itemgroup.Unspsc }
     * 
     */
    public Xmlreceipt.Itemlist.Item.Itemgroup.Unspsc createXmlreceiptItemlistItemItemgroupUnspsc() {
        return new Xmlreceipt.Itemlist.Item.Itemgroup.Unspsc();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Itemlist.Item.Itemgroup.Cpv }
     * 
     */
    public Xmlreceipt.Itemlist.Item.Itemgroup.Cpv createXmlreceiptItemlistItemItemgroupCpv() {
        return new Xmlreceipt.Itemlist.Item.Itemgroup.Cpv();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Itemlist.Item.Itemgroup.Sellercategory }
     * 
     */
    public Xmlreceipt.Itemlist.Item.Itemgroup.Sellercategory createXmlreceiptItemlistItemItemgroupSellercategory() {
        return new Xmlreceipt.Itemlist.Item.Itemgroup.Sellercategory();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Total.Totalquantity }
     * 
     */
    public Xmlreceipt.Total.Totalquantity createXmlreceiptTotalTotalquantity() {
        return new Xmlreceipt.Total.Totalquantity();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Total.Totalprice }
     * 
     */
    public Xmlreceipt.Total.Totalprice createXmlreceiptTotalTotalprice() {
        return new Xmlreceipt.Total.Totalprice();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Total.Aspect }
     * 
     */
    public Xmlreceipt.Total.Aspect createXmlreceiptTotalAspect() {
        return new Xmlreceipt.Total.Aspect();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Seller.Sellerid }
     * 
     */
    public Xmlreceipt.Seller.Sellerid createXmlreceiptSellerSellerid() {
        return new Xmlreceipt.Seller.Sellerid();
    }

    /**
     * Create an instance of {@link Xmlreceipt.Seller.Aspect }
     * 
     */
    public Xmlreceipt.Seller.Aspect createXmlreceiptSellerAspect() {
        return new Xmlreceipt.Seller.Aspect();
    }

}
